name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{BOT_TOKEN}}
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Build
        run: vendor/bin/satis build satis.json ./dist

